# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12USXZGL7b0PeRUqs3FWAuIxOeTX0AuUH
"""

#basics
#Generate a list of squares of numbers from 1 to 10.
lists=[1,2,3,4,5,6,7,8,9,10]
newlist=[x**2 for x in lists]
print(newlist)

#print all even number from 1 to 20
newlist1=[x for x in range(21) if x%2==0]
print(newlist1)

#From a list of words ["apple", "banana", "kiwi", "mango"], create a new list with only the words that contain the letter “a”.
fruits=["apple","banana","kiwi","mango"]
newlist2=[x for x in fruits if "a" in x]
print(newlist)

#Given [1, 2, 3, 4, 5], replace every odd number with "odd" but keep even numbers as they are.
lists=[1,2,3,4,5]
newlist3=[x if x%2==0 else "odd" for x in lists]
print(newlist3)

#From a string "Python123", extract only the digits and put them in a list.
s = "Python123"
digits = [x for x in s if x.isdigit()]
print(digits)

#From [[1,2],[3,4],[5,6]], flatten into [1,2,3,4,5,6].
nested=[[1,2],[3,4],[5,6]]
flat=[num for sublist in nested for num in sublist]
print(flat)

#Create a list of all products i*j for i in [1,2,3] and j in [1,2,3].
i=[1,2,3]
j=[1,2,3]
product=[x*y for x in i for y in j]
print(product)

#From ["dog","cat","parrot"], extract the first letter of each word.
words=["dog","cat","parrot"]
first_letter=[x[0] for x in words]
print(first_letter)

#Given [32, 212, 98.6] (temps in °F), create a new list with Celsius values.
temp=[32,212,98.6]
cel=[x-32*5/9 for x in temp]
print(cel)

#From "datascience", generate a list of all characters except vowels.
s="datascience"
vowels="aeiou"
constants=[x for x in s if x not in vowels]
print(constants)